name: docker ci
on:
  push:
    branch:
      - dockerbranch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy source
        uses: actions/checkout@v4

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: build image
        run: docker build -t nothing .