name: docker ci
on:
  push:
    branch:
      - dockerbranch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy source
        uses: actions/checkout@v4

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: build image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/nothing .

      - name: push image
        run: docker push ${{secrets.DOCKER_USERNAME}}/nothing:latest